apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollo-demo-4
  namespace: rollo-demo
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: rollo-demo-4
  template:
    metadata:
      labels:
        app: rollo-demo-4
    spec:
      containers:
        - name: rollo
          image: quay.io/modzelewski/rollo:v1  # Image Updater will update this line
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
  strategy:
    canary:
      # Simple rolling update (no steps)
      steps: []
      maxSurge: "25%"
      maxUnavailable: "25%"
